puppetlabs/influxdb

- manifests/install.pp
We cannot manage services, packages, etc on a node other than the node
which receives the catalog, so we fail compilation in this case.
However, the fqdn was previously incorrect: it should print the local,
not remote, node.
> Fix fqdn in install error message

- lib/puppet_x/puppetlabs/influxdb/influxdb.rb
If use_ssl is nil use default otherwise use the param passed in. The old logic would always end up setting use_ssl to being true
> Check use_ssl is not nil

- README.md
- data/common.yaml
- manifests/init.pp
- spec/acceptance/install_spec.rb
This commit moves the defaults for some class parameters to module data.
These params may be shared between classes and modules, namely:
* host
* port
* default org
* default bucket
It also moves the influxdb::install to influxdb, since it is the only
Puppet class and we can use APL for the above defaults
> Use module data for shared defaults

- manifests/init.pp
Prior to this commit any yum action resulted in the following message
Loaded plugins: fastestmirror
Repository ‘influxdb2’ is missing name in configuration, using id
this was due to the yumrepo resource which creates this being missing the dscr field, which maps to name
> add DSCR to influxdb2 repo 

- lib/puppet/functions/influxdb/retrieve_token.rb
- lib/puppet_x/puppetlabs/influxdb/influxdb.rb
This commit changes the retrieve_token() function to use an admin token
on disk.  This allows it to be used as a deferred function where it will
be run on agents instead of the primary server.
Also fixes an issue where Dir.home would throw an error when running via
a service.
> Use token file on disk to fetch tokens

- manifests/init.pp
This commit splits out the service declaration into two separate cases,
installing from a repo or archive source. This ensures the package is
installed before the service tries to start.
> Fix require on influxdb service

- lib/puppet/functions/influxdb/retrieve_token.rb
This commit rescues StandardError and raises an error with the message
using Puppet.err.  It also adds the response body to the error in case
of an http error code.
> Rescue exception in retrieve_token function

- data/common.yaml
- data/os/CentOS.yaml
- data/os/RedHat.yaml
- hiera.yaml
- manifests/init.pp
> Add options to set custom influxdb repo.

- .fixtures.yml
- data/common.yaml
- data/os/Debian.yaml
- data/os/RedHat.yaml
- data/os/Ubuntu.yaml
- hiera.yaml
- manifests/init.pp
- metadata.json
* regarding to documentation Influxdata only uses one GPG key to sign paackages
fixes #13
> add debian repo support

- metadata.json
This fixes a dependency conflict with puppet/telegraf, which requires
>= 2.0.0 < 9.0.0
> Change apt dependency to >= 8.0.0

- manifests/init.pp
Prior to this commit, installing the influxdb2 package may happen before apt's sources were updated, resulting in an error.  This commit adds the Apt::Update class as a requirement so that the sources are refreshed first.
> (SUP-3705) Require Apt::Update class on Ubuntu

- manifests/init.pp
In addition to FQDN and 'localhost', permit the short hostname to be used in the InfluxDB host parameter.
> Permit short hostnames to be used

- data/common.yaml
- spec/classes/init_spec.rb
The repo key has been changed: https://www.influxdata.com/blog/linux-package-signing-key-rotation/
https://portal.influxdata.com/downloads/
```
[...]
Get:6 https://repos.influxdata.com/ubuntu focal InRelease [7.019 B]            
Err:6 https://repos.influxdata.com/ubuntu focal InRelease                      
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
Hit:7 https://packagecloud.io/sensu/stable/ubuntu focal InRelease
Reading package lists... Done
W: GPG error: https://repos.influxdata.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
E: The repository 'https://repos.influxdata.com/ubuntu focal InRelease' is no longer signed.
N: …
```
> Update influxdb repo key

- lib/puppet/provider/influxdb_auth/influxdb_auth.rb
- lib/puppet/provider/influxdb_bucket/influxdb_bucket.rb
- lib/puppet/provider/influxdb_dbrp/influxdb_dbrp.rb
- lib/puppet/provider/influxdb_label/influxdb_label.rb
- lib/puppet/provider/influxdb_org/influxdb_org.rb
- lib/puppet/provider/influxdb_setup/influxdb_setup.rb
- lib/puppet/provider/influxdb_user/influxdb_user.rb
- lib/puppet_x/puppetlabs/influxdb/influxdb.rb
- spec/classes/init_spec.rb
- spec/unit/puppet/provider/influxdb_auth/influxdb_auth_spec.rb
- spec/unit/puppet/provider/influxdb_bucket/influxdb_bucket_spec.rb
- spec/unit/puppet/provider/influxdb_dbrp/influxdb_dbrp_spec.rb
- spec/unit/puppet/provider/influxdb_label/influxdb_label_spec.rb
- spec/unit/puppet/provider/influxdb_org/influxdb_org_spec.rb
- spec/unit/puppet/provider/influxdb_setup/influxdb_setup_spec.rb
- spec/unit/puppet/provider/influxdb_user/influxdb_user_spec.rb
Prior to this commit, paginated responses from the API were not accounted for.  This created an issue when list operations returned more than the default limit of 20 objects, resulting in some of the resources not being part of the state returned by the get() method.
This commit changes the influx_get() method to handle paginated responses by recursively processing the `next` objects until they are exhausted.
> (SUP-3968) Support paginated api responses

- manifests/profile/toml.pp
prior to this commit, puppet commands like apply, lookup --compile would fail on puppet agent with module enabled
> install toml-rb gem inside puppet agent

- lib/puppet/provider/influxdb_org/influxdb_org.rb
- manifests/init.pp
- spec/unit/puppet/provider/influxdb_org/influxdb_org_spec.rb
Prior to this commit, adding the admin user as a member of an org would produce an error, since it cannot be added or removed.  This commit skips it when updating org members
> (SUP-3397) Do not add/remove the admin user

- REFERENCE.md
- manifests/profile/toml.pp
This enables people to pass additional parameters to the gem installation for puppet agent/server. A common usecase is a http proxy.
> toml installation: Support `install_options`

- metadata.json
Update to puppet 7 & update OS
> (SUP-3952) Update metadata

- manifests/init.pp
- metadata.json
The new version of this module, 6.1.2, includes a fix for ensuring that the cleanup of the archive happens.  However, this introduces an idempotency issue where it will always download and cleanup the archive.
> (SUP-4215) Add creates param to archive resource

- lib/puppet/functions/influxdb/retrieve_token.rb
- lib/puppet/provider/influxdb_auth/influxdb_auth.rb
- lib/puppet/provider/influxdb_bucket/influxdb_bucket.rb
- lib/puppet/provider/influxdb_dbrp/influxdb_dbrp.rb
- lib/puppet/provider/influxdb_label/influxdb_label.rb
- lib/puppet/provider/influxdb_org/influxdb_org.rb
- lib/puppet/provider/influxdb_user/influxdb_user.rb
- lib/puppet/type/influxdb_auth.rb
- lib/puppet/type/influxdb_bucket.rb
- lib/puppet/type/influxdb_dbrp.rb
- lib/puppet/type/influxdb_label.rb
- lib/puppet/type/influxdb_org.rb
- lib/puppet/type/influxdb_user.rb
- lib/puppet_x/puppetlabs/influxdb/influxdb.rb
- manifests/init.pp
- metadata.json
- spec/unit/puppet/provider/influxdb_auth/influxdb_auth_spec.rb
* update pdk
* lint housekeeping
* add detail to api call errors
* provider simple_get_filter support
* add admin_token support to retrieve_token function
* extend influxdb_auth, support specifying permission resource user, org, and (type) name
* extend influxdb_auth with force parameter to recreate permission
> Provider updates

- lib/puppet/functions/influxdb/retrieve_token.rb
2cff2891 added a new dispatch to retrieve_token(), but it has a typo where Errno::EACCESS should be Errno::EACCES.
> Fix Errno::EACCES typo

- data/common.yaml
removed legacy facts for puppet 8 compatibility
> (SUP-4274) Swapped legacy fact fqdn for networking.fqdn

- README.md
- data/os/Ubuntu.yaml
- metadata.json
- spec/classes/init_spec.rb
> Add Debian 11 support

- lib/puppet/provider/influxdb_auth/influxdb_auth.rb
- spec/unit/puppet/provider/influxdb_auth/influxdb_auth_spec.rb
This commit fixes creating tokens with individual buckets specified via the resource.name property.  It does so by including the id of the bucket in the api call to create the token.
> Fix tokens with named buckets
